### ISSUE TITLE
Error when using this variable on MathBasic object function

### ISSUE THREAD

**Issue by ryumada** [dicodingacademy/a276-backend-expert-labs#16]
It looks like I found an error in [these](https://github.com/dicodingacademy/a276-backend-expert-labs/commit/26436a812e4c10f91450e7d4330c38210d80f3c9#diff-446a18acc5d7d8f2876e5e6c10629b649e333fdf8167a9c11f31e2c5cb775040) codes
![Screenshot_20211219_132931](https://user-images.githubusercontent.com/28515686/146666193-51bba1d5-0d7e-4530-9da7-2c803784a36c.png)

The image below is the error produced by the codes above.
![Screenshot_20211219_133013](https://user-images.githubusercontent.com/28515686/146666200-43e1256f-b977-4480-a14d-58b6c0d5a221.png)

I've solved it by calling `MathBasic` instead of `this`. Is this the best way to solve the problem above?

Thank you

**Comment by dimasmds** [comment]
Hi @ryumada. Thank you for raising this issue.

I can confirm this was a valid issue and fixed it in [this commit](https://github.com/dicodingacademy/a276-backend-expert-labs/commit/404555b93424e0bdebaf4b8711dcfff06a528055).

The best solution is to **change the arrow function** implementation in `_validateArgs` **to a regular method/function** as the others. So, that function will be able to call by `this`.
